config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "/images/upload"
  devise_for :users, path: '', path_names: { sign_in: '/log_in', registration: '/home', password: '/forgot_password' }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "site#home"
  resources :site, only: [:home, :log_in]
  resources :activities
  resources :photos
  get '/get_image_tags' => 'clarifais#get_image_tags'
  get '/check_photo_tags' => 'activities#check_photo_tags'
  get '/home' => 'site#home'
  get '/log_in' => 'site#log_in'
  get '/log_in' => 'site#forgot_password'
end

app/models/activity.rb
class Activity < ApplicationRecord

  belongs_to :activity_creator, class_name: "User", inverse_of: :created_activities
  has_many :activity_users
  has_many :tasks, inverse_of: :activity
  accepts_nested_attributes_for :tasks, allow_destroy: true
  validates :image, :title, :description, presence: true
  validates :title, length: { in: 6..30 }
  validates :description, length: { in: 12..600}
  include ImageUploader[:image]

  def self.check_tasks(tags, activity_id)
    @activity = Activity.find(activity_id)
    @tasks = @activity.tasks.map {|task| [task.id,task.tag]}
    tags.each do |tag|
      @check = @activity.tasks.select{|task| task.tag == tag}
      break unless @check == []
    end
    return @check[0]
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  def check_photo_tags
    @image_url = params[:image_url]
    @token = Clarifai.get_token
    @token = @token[:access_token]
    @response = Clarifai.get_tags(@token, @image_url)
    @tags = @response[:tags]
    @task = Activity.check_tasks(@tags, params[:activity_id])
    respond_to do |format|
      format.js {}
    end
  end

  def index
    @activities = Activity.all
  end

  def show
    @activity_user = ActivityUser.first_or_create(user_id: current_user.id, activity_id: @activity.id)
    @photo = Photo.new
    @photo.activity_user_id = @activity_user.id
  end

  def new
    @activity = Activity.new
    9.times do
      @activity.tasks.new
    end
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.activity_creator_id = current_user.id
    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity has been successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity has been successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @activity.tasks.destroy_all
    @activity.activity_users.destroy_all
    @activity.activity_creator_id = ""
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity has been successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:image, :title, :description, :activity_creator_id, tasks_attributes: [:id, :activity_id, :image, :learning_objectives, :instructions, :hints, :tag, :_destroy])
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <div class="row">
  	<div class="col-md-4">
      <div class="box">
        <div class="field">
          <div class="activity-image">
            <%= image_tag @activity.image[:large].url(public: true) if @activity.image %>
            <%= image_tag "default-image.jpg" unless @activity.image %>
          </div>
          <%#= f.label :image %>
          <%= f.hidden_field :image, value: @activity.cached_image_data %>
          <span class="btn btn-primary btn-file">
            Upload image<%= f.file_field :image %>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-8">
			<div class="box">
        <div class="field">
          <%= f.label :title %><br>
          <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description, rows: 2 %>
        </div>
        <div class="actions">
          <%= f.submit "Save activity", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="top-box">
        <h1>Activity Tasks (max 9)</h1>
      </div>
    </div>
  </div>

  <div class="tasks">
    <%= f.fields_for :tasks do |task_fields| %>
      <%= render 'activities/form_task', task_fields: task_fields %>
    <% end %>
  </div>

<% end %>

app/views/activities/_form_photo.html.erb
<%= form_for(@photo) do |f| %>
  <div class="row">
  	<div class="col-md-4">
      <div class="box">
        <div class="field">
          <div class="photo-image">
            <%= image_tag @photo.image[:large].url(public: true) if @photo.image %>
            <%= image_tag "default-image.jpg" unless @photo.image %>
          </div>
          <%#= f.label :image %>
          <%= f.hidden_field :image, value: @photo.cached_image_data %>
          <span class="btn btn-primary btn-file">
            Capture photo<%= f.file_field :image, accept: "image/*", capture: "camera" %>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="task-wrapper"></div>
    </div>
  </div>
<% end %>

app/views/activities/_form_task.html.erb
<div class="element-<%= task_fields.index %> row">
  <div class="col-md-4">
    <div class="box">
      <div class="field">
        <div class="task-image-<%= task_fields.index %>">
          <%= image_tag @activity.tasks[task_fields.index].image[:large].url(public: true) if @activity.tasks[task_fields.index].image %>
          <%= image_tag "default-image.jpg" unless @activity.tasks[task_fields.index].image %>
        </div>
        <%#= task_fields.label :image %>
        <%= task_fields.hidden_field :image, value: @activity.tasks[task_fields.index].cached_image_data %>
        <span class="btn btn-primary btn-file">
          Upload image<%= task_fields.file_field :image %>
        </span>
        <span class="task-tag-<%= task_fields.index %>">
          <%= task_fields.label :tag %>:
          <%= task_fields.select :tag, options_for_select([@activity.tasks[task_fields.index].tag]), prompt: "undefined"%>
          <span class="task-tag-message-<%= task_fields.index %>"></span>
        </span>
      </div>
    </div>
  </div>
  <div class="col-md-8">
		<div class="box">
      <div class="field">
        <%= task_fields.label :learning_objectives %><br>
        <%= task_fields.text_area :learning_objectives, rows: 2 %>
      </div>
      <div class="field">
        <%= task_fields.label :instructions %><br>
        <%= task_fields.text_area :instructions, rows: 2 %>
      </div>
      <div class="field">
        <%= task_fields.label :hints %><br>
        <%= task_fields.text_area :hints, rows: 2 %>
      </div>
      <!-- <div class="field">
        Delete: <%= task_fields.check_box :_destroy %>
      </div> -->
    </div>
  </div>
</div>

app/views/activities/_task.html.erb
<div class="box">
  <h2>Activity Task</h2>
  <h3>Learning objectives</h3>
  <p><%= simple_format(@task.learning_objectives) %></p>
  <h3>Instructions</h3>
  <p><%= simple_format(@task.instructions) %></p>
  <h3>Hints</h3>
  <p><%= simple_format(@task.hints) %></p>
</div>

app/views/activities/check_photo_tags.js.erb
$(".task-wrapper").empty();
<% if @task %>
  $(".task-wrapper").append("<%= j render 'activities/task', task: @task %>");
<% else %>
  $(".task-wrapper").append("<div class='box'><h2>Unable to find match to task</h2><h3>Please try again</h3></div>");
<% end %>

app/views/activities/edit.html.erb
<% if @activity.errors.any? %>
  <div class="alert alert-alert">
    <button type="button" class="close" data-dismiss="alert">x</button>
      <ul>
        <% @activity.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
			<div class="top-box">
        <h1>Editing Activity</h1>
      </div>
    </div>
  </div>

    <%= render 'form', activity: @activity %>

</div>

app/views/activities/index.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-md-12">
			<div class="top-box">
        <h1>Activities</h1>
      </div>
    </div>

  </div>

    <% @activities.each do |activity| %>
      <div class="row">
    		<div class="col-md-4">
    			<div class="box">
            <%= image_tag activity.image[:large].url(public: true) if activity.image %>
            <%= image_tag "default-image.jpg" unless activity.image %>
          </div>
        </div>
        <div class="col-md-8">
    			<div class="box">
            <h2><%= activity.title %></h2>
            <p><%= simple_format(activity.description) %></p>
            <% if current_user %>
              <%= link_to 'Participate', activity_path(activity), class: "btn btn-primary" %>
              <% if activity.activity_creator_id == current_user.id %>
                <%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-primary" %>
                <%= link_to 'Destroy', activity, method: :delete, class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </div>
        </div>
    	</div>
      <br>
    <% end %>

  </div>

app/views/activities/new.html.erb
<% if @activity.errors.any? %>
  <div class="alert alert-alert">
    <button type="button" class="close" data-dismiss="alert">x</button>
      <ul>
        <% @activity.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
			<div class="top-box">
        <h1>Create Activity</h1>
      </div>
    </div>
  </div>

  <%= render 'form', activity: @activity %>

</div>

app/views/activities/show.html.erb
<% if @photo.errors.any? %>
	<div class="alert alert-alert">
		<button type="button" class="close" data-dismiss="alert">x</button>
			<ul>
				<% @photo.errors.full_messages.each do |message| %>
				<li>
					<%= message %>
				</li>
				<% end %>
			</ul>
	</div>
<% end %>

<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<div class="top-box">
				<h1>Activity</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<div class="box">
				<%= image_tag @activity.image[:large].url(public: true) if @activity.image %>
				<%= image_tag "default-image.jpg" unless @activity.image %>
			</div>
    </div>
	  <div class="col-md-8">
			<div class="box">
				<div class="activity-<%= @activity.id %>">
		      <h2><%= @activity.title %></h2>
		      <p><%= simple_format(@activity.description) %></p>

					<% if @activity.activity_creator_id == current_user.id %>
						<%= link_to 'Edit', edit_activity_path(@activity), class: "btn btn-primary" %>
						<%= link_to 'Destroy', @activity, method: :delete, class: "btn btn-primary" %>
					<% end %>
				</div>
			</div>
    </div>
	</div>

  <div class="row">
    <div class="col-md-12">
			<div class="top-box">
	      <h1>Participate</h1>
			</div>
    </div>
  </div>

  <%= render 'activities/form_photo', photo: @photo %>

</div>