config/routes.rb
Rails.application.routes.draw do
  mount ImageUploader::UploadEndpoint => "/images/upload"
  devise_for :users, path: '', path_names: { sign_in: '/log_in', registration: '/home', password: '/forgot_password' }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "site#home"
  resources :site, only: [:home, :log_in]
  resources :activities
  resources :photos
  get '/get_image_tags' => 'clarifais#get_image_tags'
  get '/check_photo_tags' => 'activities#check_photo_tags'
  get '/home' => 'site#home'
  get '/log_in' => 'site#log_in'
  get '/log_in' => 'site#forgot_password'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blender</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container-fluid">
      	<div class="row">
      		<div class="col-md-12">
      			<nav class="navbar navbar-default navbar-custom" role="navigation">
      				<div class="navbar-header">
      					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
      						 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      					</button> <a class="navbar-brand" href="/">Blender</a>
      				</div>
      				<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      					<ul class="nav navbar-nav">
      						<li>
      							<%= link_to "Home", home_path %>
      						</li>
      						<li>
      							<%= link_to 'Activities', activities_path %>
      						</li>
      					</ul>
      					<ul class="nav navbar-nav navbar-right">
                  <% if user_signed_in? %>
                    <li class="dropdown">
      							  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dashboard<strong class="caret"></strong></a>
      							<ul class="dropdown-menu">
      								<li>
      									<%= link_to 'Create activity', new_activity_path %>
      								</li>
      							</ul>
        						</li>
                    <li>
                      <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
                    </li>
                  <% else %>
                    <li>
                      <%= link_to "Login", log_in_path %>
                    </li>
                    <li>
                      <%= link_to "Register", home_path %>
                    </li>
                  <%end %>
      					</ul>
      				</div>
      			</nav>
      			<div class="jumbotron">
      				<h2>
      					Blending technology and education
      				</h2>
      				<p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor.
          			Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          			Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
          			Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.
      				</p>
      				<p>
      					<a class="btn btn-primary btn-large" href="#">Learn more</a>
      				</p>
      			</div>
      		</div>
      	</div>
    </header>
    <main>
    <%= render 'shared/flash_messages' %>
    <%= devise_error_messages! %>
    <%= yield %>
    </main>
    <footer>


      <div class="container-fluid">
      	<div class="row">
      		<div class="col-md-12">
      			<nav class="navbar navbar-default navbar-custom navbar-footer" role="navigation">
              <span class="navbar-text">
                Copyright © 2017 Blender Education
              </span>
      			</nav>
      		</div>
      	</div>
      </div>



    </footer>
  </body>
</html>